version: '3.8'

services:
  fronius-emulator:
    image: python:3.10-slim
    container_name: fronius_custom_emulator
    restart: unless-stopped
    ports:
      - "1502:1502"
    volumes:
      - ./emulator.py:/app/emulator.py
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - MODBUS_PORT=1502
      - MQTT_BROKER_HOST=mqttbroker.internal
      - MQTT_BROKER_PORT=1883
      - MQTT_BROKER_USERNAME=mqttuser
      - MQTT_BROKER_PASSWORD=mqttpassword
      - MQTT_TOPIC_CURRENT_POWER=FroniusSM/01/power_W
      - MQTT_TOPIC_TOTAL_IMPORT=FroniusSM/01/import_total_kWh
      - MQTT_TOPIC_TOTAL_EXPORT=FroniusSM/01/export_total_kWh
      - SMART_METER_SERIAL="00000002"
    command: >
      sh -c "pip install --no-cache-dir paho-mqtt==1.6.1 pyModbusTCP pymodbus==2.5.3 && python emulator.py"
